version: "3.7"
services:
  scraper:
    ports:
      - 38765:38765
  analyzer:
    ports:
      - 8080:8080
  informeddb:
    ports:
      - 5432:5432
  reverse_proxy:
    image: nginx:alpine
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ./reverse-proxy/conf
        target: /etc/nginx/conf.d
      - type: bind
        source: ./reverse-proxy/security
        target: /security
    restart: unless-stopped
