version: "3.7"
services:

  traefik:
    image: traefik:1.7-alpine
    command: --docker --docker.domain=$HOSTNAME
    ports:
      - "80:80"
      - "443:443"
    environment:
      DO_AUTH_TOKEN: ${DO_AUTH_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /www/reverse-proxy/traefik.toml:/traefik.toml
      - /www/reverse-proxy/acme.json:/acme.json
    restart: unless-stopped

  informeddb:
    volumes:
      - type: bind
        source: /pgdata
        target: /var/lib/postgresql/data

  cronkite:
    image: cdaringe/cronkite:latest
    expose:
      - "80"
    env_file:
      - informed.env
    environment:
      - PORT=80
      - DB_HOST=informeddb
      - ANALYZER_API_ENDPOINT=http://analyzer:8080/fakebox/check
      - SCRAPER_API_ENDPOINT=http://scraper:38765
    depends_on:
      - traefik
    labels:
      - "traefik.cronkite.port=80"
      - "traefik.cronkite.frontend.rule=Host:$HOSTNAME,www.$HOSTNAME"
