version: "3.7"
services:
  traefik:
    image: traefik:1.7-alpine
    command: --docker --docker.domain=$HOSTNAME
    ports:
      - "80:80"
      - "443:443"
    environment:
      DO_AUTH_TOKEN: ${DO_AUTH_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - /www/certs:/www/certs
    restart: unless-stopped

  informeddb:
    volumes:
      - type: bind
        source: /pgdata
        target: /var/lib/postgresql/data
