version: "3.7"
services:
  scraper:
    image: smarp/newspaper-api
    expose:
      - "38765"
    restart: unless-stopped
  analyzer:
    image: machinebox/fakebox
    expose:
      - "8080"
    env_file:
      - informed.env
    restart: unless-stopped
  informeddb:
    image: postgres:alpine
    env_file:
      - informed.env
    command: -c "log_statement=all" -c "log_min_error_statement=error"
    restart: unless-stopped
