FROM node:alpine
RUN mkdir /informed
WORKDIR /informed
COPY . .
RUN yarn bootstrap && \
  cd /informed/packages/ui && \
  yarn build
WORKDIR /informed/packages/cronkite
RUN yarn build -p tsconfig.production.json
CMD ["node", "./src/bin.js"]
